### PR TITLE
rig_tracks: Fill up correct number of bytes in short tracks

### LINKED ISSUE #2: rig_tracks function causing destruction of the track data following a "short" track
The [rig_tracks function](https://github.com/OpenCBM/nibtools/blob/2fbb49f729b32eec3c571260ceeca317180a6dd1/fileio.c#L1312) checks for tracks being shorter than the respective track capacity, and then attempts to fill up the short track with 0x55 bytes up to the track's capacity.

However, there is a mistake in the size/count argument for the memset invocation:
```C
if(track_length[track] < capacity[track_density[track]&3])
{
	memset(track_buffer + (track*NIB_TRACK_LENGTH) + track_length[track], 0x55, capacity[track_density[track]&3]);
	//printf("Padded %d bytes\n", capacity[track_density[track]&3]-track_length[track]);
	track_length[track] = capacity[track_density[track]&3];
}
```
The size/count argument should be `capacity[track_density[track]&3] - track_length[track]` instead of just `capacity[track_density[track]&3]`. The commented out _printf_ statement got it right... ;-)

### PR DESCRIPTION
**Pull request by elgonzo**
Fixes https://github.com/OpenCBM/nibtools/issues/2

### CODE REVIEW

**Comment by spiro-trikaliotis** [comment]
Thank you for your interest in OpenCBM and especially in nibtools.
Unfortunately, this is only a read-only copy of the nibtools sources. Pete is **not** active here. Please contact him via his own website: https://c64preservation.com/dp.php?pg=nibtools

**Comment by rittwage-zz** [comment]
Good catch!  I made this change/fix upstream on 9/13.

**Comment by spiro-trikaliotis** [comment]
@rittwage, @elgonzo, so it is ok to close this PR, right?

**Comment by rittwage-zz** [comment]
Yes

**Pull request closed without merging**
